name: New-Linter

on: push

jobs:
   super-lint:
      name: Lint code base
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

         - name:Run New-Linter
          uses:github/new-linter@v3
          env;
            DEFAULT_BRANCH:main
            GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }}
